COPY ~%MOD_FOLDER%/bonusapr~ ~override~

// THAC0
APPEND ~splprot.2da~ ~C0HT_THAC0_LTEQUALS%TAB%7%TAB%-1%TAB%0~ UNLESS ~C0HT_THAC0_LTEQUALS~
COPY_EXISTING ~splprot.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ // read column value
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0HT_THAC0_LTEQUALS~ BEGIN
	    SET C0HT_THAC0_LTEQUALS = %row%
	  END
	END

COPY_EXISTING ~clswpbon.2da~ ~override~
  COUNT_2DA_ROWS 4 rows
  FOR (index = 0 ; index < rows ; ++index) BEGIN
    SET_2DA_ENTRY index 1 4 1
  END
  PRETTY_PRINT_2DA
  BUT_ONLY

COPY_EXISTING ~wspatck.2da~ ~override~
  COUNT_2DA_COLS col_num
  READ_2DA_ENTRY 0 1 col_num row0 // read in level 1 bonuses
  READ_2DA_ENTRY 1 1 col_num row1
  READ_2DA_ENTRY 2 1 col_num row2
  READ_2DA_ENTRY 3 1 col_num row3
  READ_2DA_ENTRY 4 1 col_num row4
  READ_2DA_ENTRY 5 1 col_num row5
  FOR (index = 2 ; index < col_num ; ++index) BEGIN // write level 1 bonuses to all other levels (no apr from levelling)
    SET_2DA_ENTRY 0 index col_num row0
    SET_2DA_ENTRY 1 index col_num row1
    SET_2DA_ENTRY 2 index col_num row2
    SET_2DA_ENTRY 3 index col_num row3
    SET_2DA_ENTRY 4 index col_num row4
    SET_2DA_ENTRY 5 index col_num row5
  END
  PRETTY_PRINT_2DA
  BUT_ONLY

COPY_EXISTING ~C0APR_#.SPL~ ~OVERRIDE~
LPF ALTER_EFFECT INT_VAR match_opcode = 326 parameter2 = C0HT_THAC0_LTEQUALS END

///////////////////////////////////////////////////////////////////////////
// Set Abilities for all Fighter Kits                                    //
// This allows all previously installed fighter kits to receive the      //
// benefits of your overhaul                                             //
///////////////////////////////////////////////////////////////////////////

ACTION_IF !(FILE_EXISTS_IN_GAME ~CLABMA01.2DA~) BEGIN
	COPY ~%MOD_FOLDER%/2da/blankclab.2DA~ ~override/CLABMA01.2DA~
END

ACTION_IF !(FILE_EXISTS_IN_GAME ~CLABSO01.2DA~) BEGIN
	COPY ~%MOD_FOLDER%/2da/blankclab.2DA~ ~override/CLABSO01.2DA~
END

ACTION_IF NOT FILE_EXISTS_IN_GAME ~CLABMA02.2DA~ BEGIN
COPY_EXISTING ~CLABMA01.2DA~ ~OVERRIDE/CLABMA02.2DA~
END

ACTION_IF NOT FILE_EXISTS_IN_GAME ~CLABMA03.2DA~ BEGIN
COPY_EXISTING ~CLABMA01.2DA~ ~OVERRIDE/CLABMA03.2DA~
END

ACTION_IF NOT FILE_EXISTS_IN_GAME ~CLABMA04.2DA~ BEGIN
COPY_EXISTING ~CLABMA01.2DA~ ~OVERRIDE/CLABMA04.2DA~
END

ACTION_IF NOT FILE_EXISTS_IN_GAME ~CLABMA05.2DA~ BEGIN
COPY_EXISTING ~CLABMA01.2DA~ ~OVERRIDE/CLABMA05.2DA~
END

ACTION_IF NOT FILE_EXISTS_IN_GAME ~CLABMA06.2DA~ BEGIN
COPY_EXISTING ~CLABMA01.2DA~ ~OVERRIDE/CLABMA06.2DA~
END

ACTION_IF NOT FILE_EXISTS_IN_GAME ~CLABMA07.2DA~ BEGIN
COPY_EXISTING ~CLABMA01.2DA~ ~OVERRIDE/CLABMA07.2DA~
END

ACTION_IF NOT FILE_EXISTS_IN_GAME ~CLABMA08.2DA~ BEGIN
COPY_EXISTING ~CLABMA01.2DA~ ~OVERRIDE/CLABMA08.2DA~
END

ACTION_IF NOT FILE_EXISTS_IN_GAME ~CLABMA09.2DA~ BEGIN
COPY_EXISTING ~CLABMA01.2DA~ ~OVERRIDE/CLABMA09.2DA~
END

ACTION_FOR_EACH base_clab IN clabba01 clabdr01 clabfi01 clabmo01 clabpa01 clabpr01 clabrn01 clabth01 clabma01 clabso01 BEGIN
COPY_EXISTING ~%base_clab%.2DA~ OVERRIDE
  // Borrowed from Rogue Rebalancing
  REPLACE_TEXTUALLY ~AP_C0APR__~ ~****      ~
        LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_Increment = 1 STR_VAR f_Entry = AP_C0APR__ END
  PRETTY_PRINT_2DA
END

ACTION_FOR_EACH war_clab IN clabfi01 clabmo01 clabpa01 clabrn01 BEGIN
COPY_EXISTING ~%war_clab%.2DA~ OVERRIDE
  // Borrowed from Rogue Rebalancing
  REPLACE_TEXTUALLY ~AP_C0APF_1~ ~****      ~
  REPLACE_TEXTUALLY ~AP_C0APF_2~ ~****      ~
        LPF set_clab_2da_entries INT_VAR f_MinLevel = 7 STR_VAR f_Entry = AP_C0APF_1 END 
        LPF set_clab_2da_entries INT_VAR f_MinLevel = 13 STR_VAR f_Entry = AP_C0APF_2 END 
  PRETTY_PRINT_2DA
END

COPY_EXISTING ~KITLIST.2DA~ ~override~
  READ_2DA_ENTRIES_NOW ~fig_kitlist~ 10
  FOR (row = 1; row < fig_kitlist; row += 1) BEGIN
  READ_2DA_ENTRY_FORMER ~fig_kitlist~ row 5 kit_clab
  READ_2DA_ENTRY_FORMER ~fig_kitlist~ row 1 kit_label
  READ_2DA_ENTRY_FORMER ~fig_kitlist~ row 8 kit_class
  
    PATCH_IF FILE_EXISTS_IN_GAME ~%kit_clab%.2da~ BEGIN
      INNER_ACTION BEGIN
      COPY_EXISTING ~%kit_clab%.2DA~ override
        REPLACE_TEXTUALLY ~AP_C0APR__~ ~****      ~
        LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_Increment = 1 STR_VAR f_Entry = AP_C0APR__ END 
        PRETTY_PRINT_2DA
      BUT_ONLY
      END
  END
  
PATCH_IF (kit_class = 2) OR (kit_class = 6) OR (kit_class = 12) OR (kit_class = 20) BEGIN
    PATCH_IF FILE_EXISTS_IN_GAME ~%kit_clab%.2da~ BEGIN
      INNER_ACTION BEGIN
      COPY_EXISTING ~%kit_clab%.2DA~ override
        REPLACE_TEXTUALLY ~AP_C0APF_1~ ~****      ~
        REPLACE_TEXTUALLY ~AP_C0APF_2~ ~****      ~
        LPF set_clab_2da_entries INT_VAR f_MinLevel = 7 STR_VAR f_Entry = AP_C0APF_1 END 
        LPF set_clab_2da_entries INT_VAR f_MinLevel = 13 STR_VAR f_Entry = AP_C0APF_2 END 
        PRETTY_PRINT_2DA
      BUT_ONLY
      END
  END
END
  
  END
  
COPY_EXISTING ~KITLIST.2DA~ ~override~
  READ_2DA_ENTRIES_NOW ~fig_kitlist~ 10
  FOR (row = 1; row < fig_kitlist; row += 1) BEGIN
  READ_2DA_ENTRY_FORMER ~fig_kitlist~ row 5 kit_clab
  READ_2DA_ENTRY_FORMER ~fig_kitlist~ row 1 kit_label
  READ_2DA_ENTRY_FORMER ~fig_kitlist~ row 8 kit_class
  
    PATCH_IF FILE_EXISTS_IN_GAME ~%kit_clab%.2da~ BEGIN
      INNER_ACTION BEGIN
      COPY_EXISTING ~%kit_clab%.2DA~ override
        REPLACE_TEXTUALLY ~AP_C0APR__~ ~****      ~
        LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_Increment = 1 STR_VAR f_Entry = AP_C0APR__ END 
        PRETTY_PRINT_2DA
      END
  END
END


COPY_EXISTING_REGEXP GLOB ~^.+\.cre$~ ~override~ 
   READ_BYTE	0x273 class
   PATCH_IF ((class = 1) OR (class = 3) OR (class = 4) OR (class = 5) OR (class = 11) OR (class = 13) OR (class = 14) OR (class = 15) OR (class = 19) OR (class = 21)) BEGIN
   LPF ADD_CRE_EFFECT INT_VAR opcode = 326 target = 1 STR_VAR resource = C0APR__ END
   END
      BUT_ONLY
	  
COPY_EXISTING_REGEXP GLOB ~^.+\.itm$~ ~override~ 
   LPF ALTER_EFFECT
      INT_VAR
      silent = 1
      match_opcode = 54
      match_parameter2 = 0
      match_timing = 0
      opcode = 278
   END
   LPF ALTER_EFFECT
      INT_VAR
      silent = 1
      match_opcode = 54
      match_parameter2 = 0
      match_timing = 2
      opcode = 278
   END
   LPF ALTER_EFFECT
      INT_VAR
      silent = 1
      match_opcode = 54
      match_parameter2 = 0
      match_timing = 3
      opcode = 278
   END
   LPF ALTER_EFFECT
      INT_VAR
      silent = 1
      match_opcode = 54
      match_parameter2 = 0
      match_timing = 5
      opcode = 278
   END
   LPF ALTER_EFFECT
      INT_VAR
      silent = 1
      match_opcode = 54
      match_parameter2 = 0
      match_timing = 6
      opcode = 278
   END
   LPF ALTER_EFFECT
      INT_VAR
      silent = 1
      match_opcode = 54
      match_parameter2 = 0
      match_timing = 8
      opcode = 278
   END
   LPF ALTER_EFFECT
      INT_VAR
      silent = 1
      match_opcode = 54
      match_parameter2 = 0
      match_timing = 10
      opcode = 278
   END
      BUT_ONLY

COPY_EXISTING_REGEXP GLOB ~^.+\.spl$~ ~override~ 
   LPF ALTER_EFFECT
      INT_VAR
      silent = 1
      match_opcode = 54
      match_parameter2 = 0
      match_timing = 0
      opcode = 278
   END
   LPF ALTER_EFFECT
      INT_VAR
      silent = 1
      match_opcode = 54
      match_parameter2 = 0
      match_timing = 2
      opcode = 278
   END
   LPF ALTER_EFFECT
      INT_VAR
      silent = 1
      match_opcode = 54
      match_parameter2 = 0
      match_timing = 3
      opcode = 278
   END
   LPF ALTER_EFFECT
      INT_VAR
      silent = 1
      match_opcode = 54
      match_parameter2 = 0
      match_timing = 5
      opcode = 278
   END
   LPF ALTER_EFFECT
      INT_VAR
      silent = 1
      match_opcode = 54
      match_parameter2 = 0
      match_timing = 6
      opcode = 278
   END
   LPF ALTER_EFFECT
      INT_VAR
      silent = 1
      match_opcode = 54
      match_parameter2 = 0
      match_timing = 8
      opcode = 278
   END
   LPF ALTER_EFFECT
      INT_VAR
      silent = 1
      match_opcode = 54
      match_parameter2 = 0
      match_timing = 10
      opcode = 278
   END
      BUT_ONLY

      
ACTION_IF FILE_EXISTS_IN_GAME ~SPPR412.SPL~ THEN BEGIN
COPY_EXISTING ~SPPR412.SPL~ ~OVERRIDE~
LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 278 opcode = 54 END
END
      
ACTION_IF FILE_EXISTS_IN_GAME ~OHTMPS1.SPL~ THEN BEGIN
COPY_EXISTING ~OHTMPS1.SPL~ ~OVERRIDE~
LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 278 opcode = 54 END
END