// Shields
 COPY_EXISTING_REGEXP GLOB ~.*\.spl~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) BEGIN // avoid crashing on empty items
    READ_SHORT    0x19 hostile
		SET weapon_visual = 0
		SET remove_visual_effect = 0
		SET has_icon = 0
    PATCH_IF ((hostile BAND 0b00000100) = 0b00000000) BEGIN
			READ_LONG  0x64 ___#abil_off
    READ_SHORT 0x68 ___#abil_num
    READ_LONG  0x6a ___#fx_off
				 FOR (___#index1 = 0 ; ___#index1 < ___#abil_num ; ___#index1 = ___#index1 + 1) BEGIN
				READ_SHORT (___#abil_off + 0x1e + (0x28 * ___#index1)) ___#abil_fx_num
        READ_SHORT (___#abil_off + 0x20 + (0x28 * ___#index1)) ___#abil_fx_idx
          FOR (___#index2 = ___#abil_fx_idx ; ___#index2 < (___#abil_fx_idx + ___#abil_fx_num) ; ___#index2 = ___#index2 + 1) BEGIN
            READ_SHORT (___#fx_off + 0x30 * ___#index2) ___#opcode
            READ_BYTE (___#fx_off + 0x30 * ___#index2 + 0x02) ___#target
            READ_LONG (___#fx_off + 0x30 * ___#index2 + 0x04) ___#param1
            READ_LONG (___#fx_off + 0x30 * ___#index2 + 0x08) ___#param2
            READ_BYTE (___#fx_off + 0x30 * ___#index2 + 0x12) ___#timing
            READ_LONG (___#fx_off + 0x30 * ___#index2 + 0x14) ___#duration

        PATCH_IF (___#opcode = 142) AND (has_icon = 0) BEGIN
          SET has_icon = 1
        END

				END

        END

			FOR (___#index1 = 0 ; ___#index1 < ___#abil_num ; ___#index1 = ___#index1 + 1) BEGIN
				READ_SHORT (___#abil_off + 0x1e + (0x28 * ___#index1)) ___#abil_fx_num
        READ_SHORT (___#abil_off + 0x20 + (0x28 * ___#index1)) ___#abil_fx_idx
          FOR (___#index2 = ___#abil_fx_idx ; ___#index2 < (___#abil_fx_idx + ___#abil_fx_num) ; ___#index2 = ___#index2 + 1) BEGIN
            READ_SHORT (___#fx_off + 0x30 * ___#index2) ___#opcode
            READ_BYTE (___#fx_off + 0x30 * ___#index2 + 0x02) ___#target
            READ_BYTE (___#fx_off + 0x30 * ___#index2 + 0x03) ___#power
            READ_LONG (___#fx_off + 0x30 * ___#index2 + 0x04) ___#param1
            READ_BYTE (___#fx_off + 0x30 * ___#index2 + 0x08) ___#param2_location
            READ_BYTE (___#fx_off + 0x30 * ___#index2 + 0x0c) ___#timing
            READ_LONG (___#fx_off + 0x30 * ___#index2 + 0x0e) ___#duration
				    READ_ASCII (___#fx_off + 0x30 * ___#index2 + 0x14) ___#resource
            
	      PATCH_IF (___#opcode = 9) BEGIN

				PATCH_IF !(___#param2_location = 16) AND !(___#param2_location = 20) AND !(___#param2_location = 21) BEGIN
				  SET remove_visual_effect = 1
          WRITE_EVALUATED_ASCII (___#fx_off + 0x30 * ___#index2 + 0x14) ~#0DELETE~ (8)

        END

				PATCH_IF (___#duration >= 300) BEGIN
				SET remove_visual_effect = 1

        END
        END

		  END
      
        PATCH_IF (has_icon = 1) AND (remove_visual_effect = 1) BEGIN
          LPF DELETE_EFFECT STR_VAR match_resource = ~#0DELETE~ END
        END

        END
    END

	END
    BUT_ONLY
